// Lista de bancos de EE.UU. de uso común (para el selector con búsqueda/scroll).
// No es exhaustiva de los ~4,000 bancos del país; incluye los principales y una
// opción para escribir uno no listado. Se puede ampliar libremente.
export const BANCOS_EEUU = [
  'Chase (JPMorgan Chase)',
  'Bank of America',
  'Wells Fargo',
  'Citibank',
  'U.S. Bank',
  'PNC Bank',
  'Truist Bank',
  'Capital One',
  'TD Bank',
  'Goldman Sachs (Marcus)',
  'BMO Harris Bank',
  'Fifth Third Bank',
  'Citizens Bank',
  'KeyBank',
  'Regions Bank',
  'M&T Bank',
  'Huntington National Bank',
  'Ally Bank',
  'HSBC Bank USA',
  'American Express National Bank',
  'Discover Bank',
  'Charles Schwab Bank',
  'First Citizens Bank',
  'Comerica Bank',
  'Zions Bancorporation',
  'Synovus Bank',
  'Santander Bank',
  'First Horizon Bank',
  'Western Alliance Bank',
  'Valley National Bank',
  'New York Community Bank (Flagstar)',
  'Frost Bank',
  'BOK Financial',
  'East West Bank',
  'Pinnacle Bank',
  'Old National Bank',
  'Associated Bank',
  'Webster Bank',
  'Cadence Bank',
  'Wintrust Bank',
  'South State Bank',
  'Umpqua Bank',
  'Prosperity Bank',
  'Bank OZK',
  'Simmons Bank',
  'Texas Capital Bank',
  'Glacier Bank',
  'FirstBank',
  'Arvest Bank',
  'Banner Bank',
  'Woodforest National Bank',
  'WaFd Bank',
  'Bank of the West',
  'City National Bank',
  'Mechanics Bank',
  'Rockland Trust',
  'Fulton Bank',
  'Renasant Bank',
  'United Community Bank',
  'Trustmark National Bank',
  'WesBanco',
  'Ameris Bank',
  'Hancock Whitney Bank',
  'ConnectOne Bank',
  'Dime Community Bank',
  'Apple Bank',
  'Emigrant Bank',
  'Navy Federal Credit Union',
  'PenFed Credit Union',
  'State Employees’ Credit Union (SECU)',
  'BECU (Boeing Employees CU)',
  'SchoolsFirst Federal Credit Union',
  'Golden 1 Credit Union',
  'Alliant Credit Union',
  'America First Credit Union',
  'Chime (Bancorp/Stride)',
  'Varo Bank',
  'SoFi Bank',
  'Green Dot Bank',
  'Otro / No listado',
]
